/**
 * App update service.
 *
 * Fetches latest.json from the newest mobile-v* GitHub Release,
 * compares with current version, downloads the APK and triggers
 * system install. Android-only (iOS is protected by App Store review
 * and cannot side-load).
 *
 * Historical note: we used to read /releases/latest/download/latest.json,
 * but that breaks with prefixed tags — the latest release could be
 * a desktop or server release.  Now we query the GitHub API for the
 * most recent mobile-v* release and download latest.json from its assets.
 *
 * format of latest.json (generated by ci.yml android job):
 *   { versionName, versionCode, url, size, sha256, abi, minSdkVersion }
 */

import { Platform, Linking } from "react-native";
import * as FileSystem from "expo-file-system/legacy";

const APP_VERSION = "0.1.0";

const GITHUB_OWNER = "TYBLHQY";
const GITHUB_REPO = "siltflow";
const RELEASES_API = `https://api.github.com/repos/${GITHUB_OWNER}/${GITHUB_REPO}/releases?per_page=30`;

/** Narrow GitHub release info — only the fields we care about. */
interface GhRelease {
  tag_name: string;
  assets: { name: string; browser_download_url: string }[];
}

export interface LatestRelease {
  versionName: string;
  versionCode: number;
  url: string;
  size: number;
  sha256: string;
  abi: string;
  minSdkVersion: number;
}

export interface UpdateCheckResult {
  /** Whether there's a new version. */
  hasUpdate: boolean;
  /** Current installed version. */
  currentVersion: string;
  /** Remote version info (undefined if no update available). */
  latest?: LatestRelease;
}

/** Read the current app version (hardcoded; bumped by CI on release). */
export function getCurrentVersion(): string {
  return APP_VERSION;
}

/** Fetch the latest mobile release manifest from GitHub. */
export async function fetchLatest(): Promise<LatestRelease> {
  // ── Try the GitHub API first — look for the newest mobile-v* release ──
  try {
    const resp = await fetch(RELEASES_API);
    if (resp.ok) {
      const releases: GhRelease[] = await resp.json();
      const mobileRelease = releases.find((r) => r.tag_name.startsWith("mobile-v"));
      if (mobileRelease) {
        const latestAsset = mobileRelease.assets.find((a) => a.name === "latest.json");
        if (latestAsset) {
          const jsonResp = await fetch(latestAsset.browser_download_url);
          if (jsonResp.ok) {
            const data = await jsonResp.json();
            if (data.versionName && data.url) return data as LatestRelease;
          }
        }
      }
    }
  } catch {
    // API rate-limit or network error — fall through to the direct URL
  }

  // ── Fallback: direct download from the latest release ──────────────────
  // This only works if the most recent release happens to be a mobile one,
  // but it's better than nothing when the API is rate-limited.
  const fallback = await fetch(
    `https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/latest/download/latest.json`,
  );
  if (!fallback.ok) throw new Error(`Failed to fetch latest.json: HTTP ${fallback.status}`);
  const data = await fallback.json();
  if (!data.versionName || !data.url) {
    throw new Error("Invalid latest.json format from server");
  }
  return data as LatestRelease;
}

/** Compare remote versionName against current; return true if newer. */
export function isNewer(remoteVersion: string, localVersion: string): boolean {
  const r = remoteVersion.split(".").map(Number);
  const l = localVersion.split(".").map(Number);
  for (let i = 0; i < Math.max(r.length, l.length); i++) {
    const rn = r[i] ?? 0;
    const ln = l[i] ?? 0;
    if (rn > ln) return true;
    if (rn < ln) return false;
  }
  return false; // same version
}

/** Check for updates: fetch latest.json, compare versions. */
export async function checkForUpdates(): Promise<UpdateCheckResult> {
  const localV = getCurrentVersion();
  const latest = await fetchLatest();
  const hasUpdate = isNewer(latest.versionName, localV);
  return { hasUpdate, currentVersion: localV, latest: hasUpdate ? latest : undefined };
}

/** Download the APK to a temp file and return the local URI. */
export async function downloadUpdate(url: string, onProgress?: (pct: number) => void): Promise<string> {
  const dest = `${FileSystem.cacheDirectory}siltflow-update.apk`;
  const download = FileSystem.createDownloadResumable(
    url,
    dest,
    {},
    ({ totalBytesWritten, totalBytesExpectedToWrite }) => {
      if (totalBytesExpectedToWrite > 0 && onProgress) {
        try {
          onProgress(Math.round((totalBytesWritten / totalBytesExpectedToWrite) * 100));
        } catch {
          // ignore — prevent a callback crash from killing the download
        }
      }
    },
  );
  const result = await download.downloadAsync();
  if (!result?.uri) throw new Error("Download failed: no URI returned");
  return result.uri;
}

/** Trigger system APK installer via content:// URI. */
export async function installAPK(fileUri: string): Promise<void> {
  if (Platform.OS !== "android") {
    throw new Error("In-app APK install is only supported on Android");
  }
  // Convert file:// URI to content:// URI via expo-file-system's FileProvider
  // This avoids android.os.FileUriExposedException on API 24+.
  const contentUri = await FileSystem.getContentUriAsync(fileUri);
  await Linking.openURL(contentUri);
}

/** Quick: check for updates → download → install, return status at each step. */
export async function downloadAndInstall(
  onProgress?: (pct: number) => void,
): Promise<{ localPath: string }> {
  const { latest } = await checkForUpdates();
  if (!latest) throw new Error("No update available");
  const localPath = await downloadUpdate(latest.url, onProgress);
  // Give a brief moment for the progress bar to visually reach 100% before
  // the content:// URI triggers the system installer dialog.
  await new Promise((resolve) => setTimeout(resolve, 300));
  await installAPK(localPath);
  return { localPath };
}
