import { test, expect, type Page } from "@playwright/test";
import {
  launchApp,
  seedDocument,
  seedSummary,
  seedAIConfig,
  seedAIV2Annotation,
  openDocument,
  waitForPdf,
} from "./helpers";
import { startMockAIServer, type MockAIServer } from "./mock-ai-server";
import path from "node:path";
import { fileURLToPath } from "node:url";
import Database from "better-sqlite3";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FIXTURE_PDF = path.resolve(__dirname, "fixtures", "test-350.pdf");

const SUMMARY_TEXT =
  "This is a mock AI summary generated by the E2E mock server. It captures the " +
  "document's core arguments from a language learner's perspective.";

// ---------------------------------------------------------------------------
// AI E2E tests — run against a LOCAL mock OpenAI-compatible server (no real
// API key). `seedAIConfig` points the vault's AI profile at the mock's
// baseUrl, so every click on "AI Summarize" / "Translate" issues a REAL
// fetch to the mock over http://localhost (allowed by the page CSP), and the
// app's full request → parse → render → persist path is exercised.
// ---------------------------------------------------------------------------

let mock: MockAIServer;

test.beforeAll(async () => {
  mock = await startMockAIServer();
});

test.afterAll(async () => {
  await mock.close();
});

/** Drag across the first text line to create a real text selection. */
async function selectFirstLine(window: Page) {
  const textLayer = window.locator(
    '.pdfViewer .page[data-page-number="1"] .textLayer',
  );
  await expect(textLayer).toBeVisible({ timeout: 20_000 });
  const line = textLayer
    .locator("span", { hasText: "This is content" })
    .first();
  await expect(line).toBeVisible();
  const box = await line.boundingBox();
  expect(box).not.toBeNull();
  await window.mouse.move(box!.x, box!.y + box!.height / 2);
  await window.mouse.down();
  await window.mouse.move(box!.x + 400, box!.y + box!.height / 2, {
    steps: 10,
  });
  await window.mouse.up();
}

// ---------------------------------------------------------------------------
// Test A — AI Summarize end-to-end over the mock server.
// ---------------------------------------------------------------------------

test("AI Summarize runs the full flow and persists the result", async () => {
  const { app, window, vault } = await launchApp((v) => {
    seedDocument(v, FIXTURE_PDF);
    seedAIConfig(v, { port: mock.port });
  });
  try {
    await openDocument(window, "E2E Test PDF");
    await waitForPdf(window);

    // Summary tab triggers page-text extraction; the pages toggle renders
    // once extraction completes.
    await window.getByRole("tab", { name: "Summary" }).click();
    const summaryPanel = window.getByLabel("Summary");
    const pagesToggle = window.getByRole("button", { name: /350 pages/ });
    await expect(pagesToggle).toBeVisible({ timeout: 20_000 });
    // AI Summarize gates on pageTexts being extracted. RightPanel defaults
    // selectedPages to [1] only AFTER extraction finishes; before that the
    // selection is "undefined" which renders EVERY page selected. So wait for
    // the settled state: page 1 selected (mauve) but page 2 NOT selected.
    const page1Btn = summaryPanel.getByRole("button", {
      name: "1",
      exact: true,
    });
    const page2Btn = summaryPanel.getByRole("button", {
      name: "2",
      exact: true,
    });
    await expect(page1Btn).toHaveClass(/bg-ctp-mauve\/10/);
    await expect(page2Btn).not.toHaveClass(/bg-ctp-mauve\/10/);

    // Click AI Summarize → real fetch to the mock server → summary renders.
    await window.getByRole("button", { name: "AI Summarize" }).click();
    await expect(window.getByText(SUMMARY_TEXT, { exact: true })).toBeVisible({
      timeout: 20_000,
    });
    await expect(window.getByText("AI-generated")).toBeVisible();
    // Toast text — exact match, since SUMMARY_TEXT itself contains the
    // substring "summary generated" (…mock AI summary generated by…).
    await expect(
      window.getByText("Summary generated", { exact: true }),
    ).toBeVisible();

    // The summary was persisted to the vault DB (is_ai_generated=1).
    await expect
      .poll(
        () => {
          const db = new Database(path.join(vault, ".siltflow", "data.db"));
          const row = db
            .prepare("SELECT text, is_ai_generated, source_lang FROM summaries")
            .get() as
            | { text: string; is_ai_generated: number; source_lang: string }
            | undefined;
          db.close();
          return row;
        },
        { timeout: 15_000 },
      )
      .toEqual(
        expect.objectContaining({
          text: SUMMARY_TEXT,
          is_ai_generated: 1,
          source_lang: "en-US",
        }),
      );
  } finally {
    await app.close();
  }
});

// ---------------------------------------------------------------------------
// Test B — translate a freshly-created annotation via the V2 pipeline.
// ---------------------------------------------------------------------------

test("translate uses the V2 two-stage pipeline and persists ai_results", async () => {
  const { app, window, vault } = await launchApp((v) => {
    const docId = seedDocument(v, FIXTURE_PDF);
    seedAIConfig(v, { port: mock.port });
    // Translation requires an existing summary (batch/single both gate on it).
    seedSummary(v, docId, SUMMARY_TEXT);
  });
  try {
    await openDocument(window, "E2E Test PDF");
    await waitForPdf(window);

    // selectionMode was seeded as "manual" → SelectionTip appears after select.
    await selectFirstLine(window);
    await window.getByTitle("Add as annotation").click();

    // The annotation card appears untranslated (Base view) in the panel.
    await window.getByRole("tab", { name: "Annotations" }).click();
    const card = window.locator("[data-annotation-id]").first();
    await expect(card).toBeVisible({ timeout: 20_000 });
    await expect(card).toContainText("This is content");

    // Click the card's Translate button (Sparkles icon in the action bar).
    // AITranslateCard renders the translate button with title="Translate".
    await card.getByTitle("Translate").click();

    // The V2 pipeline makes two mock calls (input → output). The card shows
    // the "v2" badge (core header, always visible) once translation lands.
    await expect(card.getByText("v2", { exact: true })).toBeVisible({
      timeout: 20_000,
    });

    // The output translation renders in the collapsible DETAILS area, which
    // starts collapsed — click the card's source text to expand it first.
    await card.getByText("This is content").first().click();
    await expect(card.getByText("这是内容")).toBeVisible({ timeout: 10_000 });

    // The ai_results row was persisted with version=2 (survives a restart).
    await expect
      .poll(
        () => {
          const db = new Database(path.join(vault, ".siltflow", "data.db"));
          const row = db
            .prepare("SELECT data, version FROM ai_results LIMIT 1")
            .get() as { data: string; version: number } | undefined;
          db.close();
          return row;
        },
        { timeout: 15_000 },
      )
      .toEqual(
        expect.objectContaining({
          version: 2,
        }),
      );
  } finally {
    await app.close();
  }
});

// ---------------------------------------------------------------------------
// Test C — a seeded V2 card renders correctly + AI config appears in Settings.
// ---------------------------------------------------------------------------

test("seeded V2 annotation renders details and AI config shows in Settings", async () => {
  const { app, window } = await launchApp((v) => {
    const docId = seedDocument(v, FIXTURE_PDF);
    seedAIConfig(v, { port: mock.port });
    seedAIV2Annotation(v, docId, {
      id: "v2-word",
      pageNumber: 1,
      text: "endure",
      aiResult: {
        input: {
          text: "endure",
          normalized: "endure",
          source_lang: "en-US",
          type: "word",
          lemma: "endure",
        },
        context: null,
        output: {
          meanings: [
            { pos: "VERB", translation: "忍受" },
            { pos: "VERB", translation: "持久" },
          ],
          definitions: [
            {
              pos: "VERB",
              definition: {
                source: "to suffer through something difficult",
                target: "忍受艰难之事",
              },
            },
          ],
          examples: [
            {
              sentence: "She endured the long journey.",
              translation: "她忍受了漫长的旅程。",
            },
          ],
          collocations: [{ phrase: "endure pain", translation: "忍受疼痛" }],
          synonyms: ["tolerate", "withstand"],
          cefr: "B2",
        },
      },
    });
  });
  try {
    await openDocument(window, "E2E Test PDF");
    await waitForPdf(window);

    // The seeded V2 card renders in the Annotations tab with the v2 badge.
    await window.getByRole("tab", { name: "Annotations" }).click();
    const card = window.locator('[data-annotation-id="v2-word"]');
    await expect(card).toBeVisible({ timeout: 20_000 });
    await expect(card.getByText("v2", { exact: true })).toBeVisible();
    // Source text is the normalized input (always the header line).
    await expect(card.getByText("endure").first()).toBeVisible();

    // Details are collapsed initially (collapsible card). Click the card's
    // source text (bubbles to the upper-area toggle) to expand the details.
    await card.getByText("endure").first().click();
    await expect(card.getByText("CEFR & Lemma")).toBeVisible({
      timeout: 10_000,
    });
    await expect(card.getByText("B2")).toBeVisible();
    await expect(card.getByText("Meanings")).toBeVisible();
    // 忍受 appears as a meaning AND inside a definition — .first() dodges
    // strict mode; we only need to prove V2 detail content rendered.
    await expect(card.getByText("忍受").first()).toBeVisible();
    await expect(card.getByText("Definitions")).toBeVisible();

    // The seeded AI profile shows up in Settings → AI.
    await window.getByTitle("Settings").click();
    const dialog = window.locator('[role="dialog"]:visible');
    await expect(dialog.getByText("AI Providers")).toBeVisible();
    // "Mock AI" appears in the profile card AND in each task-assignment
    // dropdown option — .first() dodges strict mode.
    await expect(dialog.getByText("Mock AI").first()).toBeVisible();
    await expect(dialog.getByText("custom").first()).toBeVisible();
    // Task Assignment lists all three AI tasks.
    await expect(dialog.getByText("Task Assignment")).toBeVisible();
    await expect(dialog.getByText("Summarize")).toBeVisible();
    await expect(dialog.getByText("Translate (Input)")).toBeVisible();
    await expect(dialog.getByText("Translate (Output)")).toBeVisible();
  } finally {
    await app.close();
  }
});
