import { test, expect } from "@playwright/test";
import {
  launchApp,
  seedDocument,
  seedAnnotation,
  seedAIV2Annotation,
  seedSummary,
  seedAIConfig,
  makePosition,
  openDocument,
  waitForPdf,
} from "./helpers";
import {
  makeCompact,
  makeTall,
  longText,
  expectCardsAligned,
} from "./annotations-helpers";
import { startMockAIServer, type MockAIServer } from "./mock-ai-server";
import path from "node:path";
import { fileURLToPath } from "node:url";
import Database from "better-sqlite3";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FIXTURE_PDF = path.resolve(__dirname, "fixtures", "test-350.pdf");

const SUMMARY_TEXT =
  "This is a mock AI summary generated by the E2E mock server. It captures the " +
  "document's core arguments from a language learner's perspective.";

let mock: MockAIServer;

test.beforeAll(async () => {
  mock = await startMockAIServer();
});

test.afterAll(async () => {
  await mock.close();
});

/**
 * Regression guard for the UNTRANSLATED card state in the virtualized
 * annotations list. The add/delete alignment spec (annotations-alignment)
 * seeds only V2 cards, so it never exercises the blank-slate card (no
 * aiResult) or its UNTRANSLATED → V2 height transition. Seed an interleaved
 * V2 + UNTRANSLATED list, run the same expand/delete/insert dance, then
 * translate cards — a visible one and a batch of mostly-off-screen ones — and
 * assert the boxes stay contiguous throughout, including after scrolling to
 * the bottom where cards translated while virtualized out.
 */
test("untranslated cards stay aligned through translate + interleaved mutations", async () => {
  const { app, window, vault } = await launchApp((vault) => {
    const docId = seedDocument(vault, FIXTURE_PDF);
    seedSummary(vault, docId, SUMMARY_TEXT);
    seedAIConfig(vault, { port: mock.port });
    // Every 3rd card is UNTRANSLATED (no ai_results row), the rest V2. Vary
    // heights within both kinds so every index slot has a distinct resting
    // height, mirroring the V2-only alignment seed.
    for (let i = 0; i < 120; i++) {
      if (i % 3 === 0) {
        seedAnnotation(vault, docId, {
          id: `ann-${i}`,
          pageNumber: 1 + i,
          text: i % 6 === 3 ? longText(`u${i}`) : `untranslated ${i}`,
          position: makePosition(1 + i),
        });
      } else {
        seedAIV2Annotation(vault, docId, {
          id: `ann-${i}`,
          pageNumber: 1 + i,
          text: i % 2 === 1 ? longText(`w${i}`) : `word ${i}`,
          aiResult: i % 2 === 1 ? makeTall(`w${i}`) : makeCompact(`w${i}`),
          position: makePosition(1 + i),
        });
      }
    }
  });

  try {
    await openDocument(window, "E2E Test PDF");
    await waitForPdf(window);
    await window.getByRole("tab", { name: "Annotations" }).click();
    await expect(window.locator('[data-annotation-id="ann-0"]')).toBeVisible();

    // Track the live card total (seed 120, −2 on delete, +1 per manual add).
    // After the final batch translate every surviving card is V2 with an
    // ai_results row, so this doubles as the DB-count completion signal.
    let totalCards = 120;

    // Which cards are currently expanded — bookkeeping; a click always flips
    // the real card. Only call toggleCard on V2 ids (i % 3 !== 0): UNTRANSLATED
    // cards have no collapsible details, so the click is a no-op.
    const expanded = new Set<string>();
    const toggleCard = async (id: string) => {
      const card = window.locator(`[data-annotation-id="${id}"]`);
      await expect(card).toBeVisible();
      const box = await card.boundingBox();
      if (!box) throw new Error(`card ${id} has no box`);
      await card.click({ position: { x: box.width / 2, y: 20 } });
      if (expanded.has(id)) expanded.delete(id);
      else expanded.add(id);
      // 200ms grid-template-rows animation + ResizeObserver settle.
      await window.waitForTimeout(350);
    };

    const deleteCard = async (id: string) => {
      const card = window.locator(`[data-annotation-id="${id}"]`);
      await expect(card).toBeVisible();
      await card.locator('button[title="Delete"]').click();
      await expect(card).toBeHidden({ timeout: 5_000 });
      await window.waitForTimeout(300);
      expanded.delete(id);
      totalCards -= 1;
    };

    const addManualAnnotation = async (text: string) => {
      await window.getByTitle("Add manual annotation").click();
      const dialog = window.getByRole("dialog");
      await dialog.locator("textarea").fill(text);
      await dialog.getByRole("button", { name: "Add" }).click();
      await expect(dialog).toBeHidden({ timeout: 5_000 });
      await window.waitForTimeout(300);
      totalCards += 1;
    };

    // Baseline: the mixed 120-card list must render aligned.
    await expectCardsAligned(window);

    // Expand/collapse V2 cards so tall (expanded) cards sit above UNTRANSLATED
    // ones, then delete both kinds and insert a manual card at the top.
    await toggleCard("ann-1"); // V2 tall
    await toggleCard("ann-4"); // V2 compact
    await toggleCard("ann-1"); // collapse
    await toggleCard("ann-5"); // V2 tall
    await expectCardsAligned(window);

    await deleteCard("ann-0"); // UNTRANSLATED
    await deleteCard("ann-2"); // V2 compact
    await expectCardsAligned(window);

    await addManualAnnotation("fresh manual word");
    await expectCardsAligned(window);

    // Translate a VISIBLE UNTRANSLATED card (long text → mock returns a short
    // phrase, so the card SHRINKS) — the height transition must not break
    // contiguity.
    const untranslatedCard = window.locator('[data-annotation-id="ann-3"]');
    await expect(untranslatedCard).toBeVisible();
    await untranslatedCard.getByTitle("Translate").click();
    await expect(untranslatedCard.getByText("v2", { exact: true })).toBeVisible(
      { timeout: 20_000 },
    );
    await window.waitForTimeout(350);
    await expectCardsAligned(window);

    // Batch-translate the rest — mostly below the fold, so they change state
    // while virtualized out. Wait for every translation to persist, then the
    // list must be aligned.
    await window.getByTitle("Translate all untranslated annotations").click();
    await expect
      .poll(
        () => {
          const db = new Database(path.join(vault, ".siltflow", "data.db"));
          const row = db
            .prepare("SELECT COUNT(*) AS n FROM ai_results")
            .get() as { n: number };
          db.close();
          return row.n;
        },
        { timeout: 20_000 },
      )
      .toBe(totalCards);
    await window.waitForTimeout(350);
    await expectCardsAligned(window);

    // Scroll to the bottom — off-screen cards mounted as V2 and re-measured.
    // Scope the viewport to the one actually containing the annotation cards
    // (the page has several Radix scroll areas, e.g. the Docs tree).
    const viewport = window.locator(
      "[data-radix-scroll-area-viewport]:has([data-annotation-id])",
    );
    for (let i = 0; i < 3; i++) {
      await viewport.evaluate((el) => {
        el.scrollTop = el.scrollHeight;
      });
      await window.waitForTimeout(50);
    }
    await expect(window.locator('[data-annotation-id="ann-119"]')).toBeVisible({
      timeout: 10_000,
    });
    await window.waitForTimeout(350);
    await expectCardsAligned(window);
  } finally {
    await app.close();
  }
});
