import { createServer, type Server } from "node:http";

// ---------------------------------------------------------------------------
// Mock OpenAI-compatible server for E2E AI tests.
//
// Siltflow's `chatCompletion` (src/lib/ai.ts) talks to any OpenAI-compatible
// `baseUrl` via the OpenAI SDK. The CSP in index.html allows `http://localhost:*`
// connect-src, so pointing a profile's baseUrl at this server lets the E2E tests
// exercise the REAL request → parse → render → persist path without a real API
// key. The server inspects the request messages and returns the appropriate
// JSON for whichever pipeline stage is being called:
//
//   summarize          user msg starts with "[Page 1]"      → {summary, source_lang}
//   translate (input)  user msg contains "Text: "           → AIAnnotationInputV2
//   translate (output) user msg contains "Input: {...}"     → PhraseOutputV2
//
// Responses are intentionally minimal-but-valid Chat Completions payloads
// (finish_reason "stop", no stream) so the SDK's non-streaming path parses them.
// ---------------------------------------------------------------------------

interface ChatMessage {
  role: string;
  content: string;
}

const CORS_HEADERS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization",
};

const SUMMARY_TEXT =
  "This is a mock AI summary generated by the E2E mock server. It captures the " +
  "document's core arguments from a language learner's perspective.";

const INPUT_RESULT = {
  text: "This is content",
  normalized: "This is content",
  source_lang: "en-US",
  type: "phrase",
  lemma: null,
};

const OUTPUT_RESULT = {
  translation: "这是内容",
  examples: [
    {
      sentence: "This is content for the learners.",
      translation: "这是给学习者的内容。",
    },
  ],
};

/** Build an OpenAI-compatible chat.completion response body. */
function completion(content: string): string {
  return JSON.stringify({
    id: "chatcmpl-mock-e2e",
    object: "chat.completion",
    created: 1_700_000_000,
    model: "mock-model",
    choices: [
      {
        index: 0,
        message: { role: "assistant", content },
        finish_reason: "stop",
      },
    ],
    usage: { prompt_tokens: 1, completion_tokens: 1, total_tokens: 2 },
  });
}

/** Pick the JSON `content` for a request based on its user message text. */
function pickContent(messages: ChatMessage[]): string {
  const userMsg = messages.find((m) => m.role === "user")?.content ?? "";
  if (userMsg.startsWith("[Page 1]")) {
    return JSON.stringify({
      summary: SUMMARY_TEXT,
      source_lang: "en-US",
    });
  }
  if (userMsg.includes("Text: ")) {
    return JSON.stringify(INPUT_RESULT);
  }
  // Everything else is the V2 output-AI stage (its user message contains
  // "Input: {...}" after the optional CONTEXT block).
  return JSON.stringify(OUTPUT_RESULT);
}

export interface MockAIServer {
  port: number;
  baseUrl: string;
  /** Total /chat/completions requests served since startup. Lets tests assert
   *  the short-circuit path (sentence/word counts differ by whether the input
   *  AI round-trip was skipped). */
  requestCount: number;
  close: () => Promise<void>;
}

/**
 * Start the mock server on an ephemeral localhost port. Callers must call
 * `close()` in a finally / afterAll. `port` is available after the await so a
 * test can seed it into the vault config BEFORE the app launches.
 */
export function startMockAIServer(): Promise<MockAIServer> {
  const state = { requestCount: 0 };
  const server: Server = createServer((req, res) => {
    // Preflight — the renderer is a browser, the SDK may send CORS preflight.
    if (req.method === "OPTIONS") {
      res.writeHead(204, CORS_HEADERS);
      res.end();
      return;
    }
    if (req.method !== "POST" || !req.url?.includes("/chat/completions")) {
      res.writeHead(404, CORS_HEADERS);
      res.end(JSON.stringify({ error: "not found" }));
      return;
    }
    state.requestCount++;

    let body = "";
    req.on("data", (chunk) => (body += chunk));
    req.on("end", () => {
      const payload = JSON.parse(body || "{}") as {
        messages?: ChatMessage[];
      };
      const content = pickContent(payload.messages ?? []);
      res.writeHead(200, {
        ...CORS_HEADERS,
        "Content-Type": "application/json",
      });
      res.end(completion(content));
    });
  });

  return new Promise((resolve, reject) => {
    server.once("error", reject);
    // Bind the dual-stack wildcard so the server accepts BOTH IPv4 (127.0.0.1)
    // and IPv6 (::1) — `localhost` may resolve to either depending on the
    // machine's /etc/hosts (here it resolves to ::1). The CSP in index.html
    // allows `http://localhost:*`, and Node's default server listens on
    // 0.0.0.0; binding "::" with dual-stack covers both address families.
    server.listen(0, "::", () => {
      const address = server.address();
      if (!address || typeof address === "string") {
        reject(new Error("mock server failed to bind a port"));
        return;
      }
      const port = address.port;
      resolve({
        port,
        baseUrl: `http://localhost:${port}/v1`,
        get requestCount() {
          return state.requestCount;
        },
        close: () =>
          new Promise<void>((res, rej) => {
            server.close((err) => {
              if (err) rej(err);
              else res();
            });
          }),
      });
    });
  });
}
