export interface DocSummary {
  /** User-editable or AI-generated summary text. */
  text: string;
  /** Whether the summary was last generated by AI (vs manually typed). */
  isAiGenerated: boolean;
  /** Detected source language (BCP 47), set after AI summarization. */
  sourceLang?: string;
  /** Key vocabulary extracted from the document (for learners). */
  keyVocabulary?: { term: string; cefr?: string }[];
  /** One-sentence core idea. */
  gist?: string;
}
