import { create } from "zustand"

export interface DocSummary {
  /** User-editable or AI-generated summary text. */
  text: string
  /** Whether the summary was last generated by AI (vs manually typed). */
  isAiGenerated: boolean
}

interface SummaryState {
  /** Per-document summaries, keyed by documentId. */
  summaries: Record<string, DocSummary>

  /**
   * Cached per-page text for each document, keyed by documentId.
   * Indexed 0-based — page N is at index N-1.
   */
  pageTexts: Record<string, string[]>

  /**
   * User-selected page numbers (1-based) for each document.
   * undefined = all pages (show toggle as "all").
   */
  selectedPages: Record<string, number[] | undefined>

  setSummary: (documentId: string, text: string, isAiGenerated?: boolean) => void
  clearSummary: (documentId: string) => void
  setPageTexts: (documentId: string, texts: string[]) => void
  setSelectedPages: (documentId: string, pages: number[] | undefined) => void
}


async function persistSummary(documentId: string, text: string, isAiGenerated: boolean) {
  window.siltflow.summaries.save({ documentId, text, isAiGenerated })
}

export const useSummaryStore = create<SummaryState>((set) => ({
  summaries: {},
  pageTexts: {},
  selectedPages: {},

  setSummary: (documentId, text, isAiGenerated = false) => {
    persistSummary(documentId, text, isAiGenerated)
    set((s) => ({
      summaries: { ...s.summaries, [documentId]: { text, isAiGenerated } },
    }))
  },

  clearSummary: (documentId) => {
    window.siltflow.summaries.delete(documentId)
    set((s) => {
      const next = { ...s.summaries }
      delete next[documentId]
      return { summaries: next }
    })
  },

  setPageTexts: (documentId, texts) =>
    set((s) => ({
      pageTexts: { ...s.pageTexts, [documentId]: texts },
    })),

  setSelectedPages: (documentId, pages) =>
    set((s) => ({
      selectedPages: { ...s.selectedPages, [documentId]: pages },
    })),
}))

/** Call once on app boot to restore summaries from backend. */
export async function loadSummariesFromVault() {
  // Load all documents' summaries one by one via the IPC.
  // In the future this could be a bulk endpoint.
  try {
    const docs = await window.siltflow.documents.list()
    const summaries: Record<string, DocSummary> = {}
    for (const doc of docs) {
      const s = await window.siltflow.summaries.get(doc.id)
      if (s) {
        summaries[doc.id] = { text: s.text, isAiGenerated: !!s.is_ai_generated }
      }
    }
    useSummaryStore.setState({ summaries })
  } catch { /* ignore */ }
}
