import { create } from "zustand"

export interface DocSummary {
  /** User-editable or AI-generated summary text. */
  text: string
  /** Whether the summary was last generated by AI (vs manually typed). */
  isAiGenerated: boolean
}

interface SummaryState {
  /** Per-document summaries, keyed by documentId. */
  summaries: Record<string, DocSummary>

  /**
   * Cached per-page text for each document, keyed by documentId.
   * Indexed 0-based — page N is at index N-1.
   */
  pageTexts: Record<string, string[]>

  /**
   * User-selected page numbers (1-based) for each document.
   * undefined = all pages (show toggle as "all").
   */
  selectedPages: Record<string, number[] | undefined>

  setSummary: (documentId: string, text: string, isAiGenerated?: boolean) => void
  clearSummary: (documentId: string) => void
  setPageTexts: (documentId: string, texts: string[]) => void
  setSelectedPages: (documentId: string, pages: number[] | undefined) => void
}

const STORAGE_KEY = "documentSummaries"

function persistSummaries(summaries: Record<string, DocSummary>) {
  window.siltflow.vaultConfigSet({ [STORAGE_KEY]: summaries })
}

export const useSummaryStore = create<SummaryState>((set) => ({
  summaries: {},
  pageTexts: {},
  selectedPages: {},

  setSummary: (documentId, text, isAiGenerated = false) =>
    set((s) => {
      const next = { ...s.summaries, [documentId]: { text, isAiGenerated } }
      persistSummaries(next)
      return { summaries: next }
    }),

  clearSummary: (documentId) =>
    set((s) => {
      const next = { ...s.summaries }
      delete next[documentId]
      persistSummaries(next)
      return { summaries: next }
    }),

  setPageTexts: (documentId, texts) =>
    set((s) => ({
      pageTexts: { ...s.pageTexts, [documentId]: texts },
    })),

  setSelectedPages: (documentId, pages) =>
    set((s) => ({
      selectedPages: { ...s.selectedPages, [documentId]: pages },
    })),
}))

/** Call once on app boot to restore summaries from vault. */
export async function loadSummariesFromVault() {
  try {
    const cfg = await window.siltflow.vaultConfigGet()
    const saved = (cfg as Record<string, unknown>)[STORAGE_KEY]
    if (saved && typeof saved === "object") {
      useSummaryStore.setState({ summaries: saved as Record<string, DocSummary> })
    }
  } catch { /* ignore */ }
}
